{{- if .Values.analytics.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "harz-storage.fullname" . }}-postgres
  labels:
    {{- include "harz-storage.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "harz-storage.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        {{- include "harz-storage.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: database
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_DB
          value: {{ .Values.analytics.database.name | quote }}
        - name: POSTGRES_USER
          value: {{ .Values.analytics.database.user | quote }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.analytics.database.password | quote }}
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - {{ .Values.analytics.database.user }}
            - -d
            - {{ .Values.analytics.database.name }}
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - {{ .Values.analytics.database.user }}
            - -d
            - {{ .Values.analytics.database.name }}
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          {{- toYaml .Values.analytics.database.resources | nindent 10 }}
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: {{ include "harz-storage.fullname" . }}-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "harz-storage.fullname" . }}-postgres
  labels:
    {{- include "harz-storage.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  selector:
    {{- include "harz-storage.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
  ports:
  - port: 5432
    targetPort: postgres
    protocol: TCP
    name: postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "harz-storage.fullname" . }}-postgres-pvc
  labels:
    {{- include "harz-storage.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.analytics.database.storage | quote }}
  {{- if .Values.analytics.database.storageClass }}
  storageClassName: {{ .Values.analytics.database.storageClass | quote }}
  {{- end }}
{{- end }}
