{{- if .Values.analytics.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "harz-storage.fullname" . }}-umami
  labels:
    {{- include "harz-storage.labels" . | nindent 4 }}
    app.kubernetes.io/component: analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "harz-storage.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: analytics
  template:
    metadata:
      labels:
        {{- include "harz-storage.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: analytics
    spec:
      containers:
      - name: umami
        image: ghcr.io/umami-software/umami:postgresql-latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: DATABASE_URL
          value: "postgresql://{{ .Values.analytics.database.user }}:{{ .Values.analytics.database.password }}@{{ include "harz-storage.fullname" . }}-postgres:5432/{{ .Values.analytics.database.name }}"
        - name: DATABASE_TYPE
          value: "postgresql"
        - name: APP_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "harz-storage.fullname" . }}-umami-secret
              key: app-secret
        livenessProbe:
          httpGet:
            path: /api/heartbeat
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/heartbeat
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          {{- toYaml .Values.analytics.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "harz-storage.fullname" . }}-umami
  labels:
    {{- include "harz-storage.labels" . | nindent 4 }}
    app.kubernetes.io/component: analytics
spec:
  selector:
    {{- include "harz-storage.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: analytics
  ports:
  - port: 3000
    targetPort: http
    protocol: TCP
    name: http
---
{{- if .Values.analytics.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "harz-storage.fullname" . }}-umami
  labels:
    {{- include "harz-storage.labels" . | nindent 4 }}
    app.kubernetes.io/component: analytics
  {{- with .Values.analytics.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.analytics.ingress.tls }}
  tls:
    {{- range .Values.analytics.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.analytics.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "harz-storage.fullname" $ }}-umami
                port:
                  number: 3000
          {{- end }}
    {{- end }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "harz-storage.fullname" . }}-umami-secret
  labels:
    {{- include "harz-storage.labels" . | nindent 4 }}
    app.kubernetes.io/component: analytics
type: Opaque
data:
  app-secret: {{ .Values.analytics.appSecret | b64enc | quote }}
{{- end }}
