replicaCount: 2

image:
  repository: harz-storage
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: nginx
  host: harz-storage.local
  tls: false

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

env:
  NODE_ENV: production
  API_URL: ""

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

# Analytics configuration (Umami)
analytics:
  enabled: false
  appSecret: "change-me-in-production"
  
  database:
    name: "umami"
    user: "umami"
    password: "change-me-in-production"
    storage: "10Gi"
    storageClass: ""
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"
  
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  
  ingress:
    enabled: false
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - host: analytics.example.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: analytics-tls
        hosts:
          - analytics.example.com
