name: Release

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: "Version bump type"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write
  actions: read
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run tests
        run: npm test

      - name: Build application
        run: npm run build

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Bump version
        id: version
        run: |
          VERSION_TYPE="${{ github.event.inputs.version_type }}"
          NEW_VERSION=$(npm version $VERSION_TYPE --no-git-tag-version)
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "version_number=${NEW_VERSION#v}" >> $GITHUB_OUTPUT

      - name: Generate changelog
        run: |
          npm run changelog:generate
          git add CHANGELOG.md

      - name: Update Helm chart version
        run: |
          sed -i 's/^version:.*/version: ${{ steps.version.outputs.version_number }}/' helm/Chart.yaml
          sed -i 's/^appVersion:.*/appVersion: "${{ steps.version.outputs.version_number }}"/' helm/Chart.yaml

      - name: Commit version bump
        run: |
          git add package.json package-lock.json helm/Chart.yaml CHANGELOG.md
          git commit -m "chore: bump version to ${{ steps.version.outputs.new_version }} [skip ci]"
          git tag ${{ steps.version.outputs.new_version }}

      - name: Push changes
        run: |
          # Create and push to a temporary branch first
          TEMP_BRANCH="release-${{ steps.version.outputs.version_number }}-$(date +%s)"
          git checkout -b $TEMP_BRANCH
          git push origin $TEMP_BRANCH
          
          # Create PR to main branch
          gh pr create \
            --title "chore: release ${{ steps.version.outputs.new_version }}" \
            --body "Automated release PR for version ${{ steps.version.outputs.new_version }}" \
            --base main \
            --head $TEMP_BRANCH
          
          # Push the tag directly (tags aren't protected)
          git push origin ${{ steps.version.outputs.new_version }}
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Build Docker image
        run: |
          docker build -t harz-storage:${{ steps.version.outputs.version_number }} .
          docker tag harz-storage:${{ steps.version.outputs.version_number }} harz-storage:latest

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          path: ./
          format: spdx-json
          output-file: sbom-${{ steps.version.outputs.version_number }}.spdx.json

      - name: Run Trivy container scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: harz-storage:${{ steps.version.outputs.version_number }}
          format: sarif
          output: trivy-results-${{ steps.version.outputs.version_number }}.sarif

      - name: Generate dependency report
        run: |
          npm audit --audit-level=moderate --json > security-audit-${{ steps.version.outputs.version_number }}.json || true

      - name: Package Helm chart
        run: |
          helm package helm/ --version ${{ steps.version.outputs.version_number }}

      - name: Generate checksums
        run: |
          sha256sum harz-storage-${{ steps.version.outputs.version_number }}.tgz > checksums-${{ steps.version.outputs.version_number }}.txt

      - name: Create GitHub Release
        run: |
          CHANGELOG=""
          if [ -f CHANGELOG.md ]; then
            CHANGELOG=$(sed -n "/## \[${{ steps.version.outputs.version_number }}\]/,/## \[/p" CHANGELOG.md | head -n -1 | tail -n +2)
          else
            CHANGELOG="Release ${{ steps.version.outputs.new_version }}"
          fi
          
          gh release create ${{ steps.version.outputs.new_version }} \
            --title "Release ${{ steps.version.outputs.new_version }}" \
            --notes "## Changes
          $CHANGELOG

          ## Security Artifacts
          - 📋 SBOM: \`sbom-${{ steps.version.outputs.version_number }}.spdx.json\`
          - 🔒 Container Scan: \`trivy-results-${{ steps.version.outputs.version_number }}.sarif\`
          - 📊 Dependency Audit: \`security-audit-${{ steps.version.outputs.version_number }}.json\`
          - ✅ Checksums: \`checksums-${{ steps.version.outputs.version_number }}.txt\`

          ## Docker Image
          \`\`\`bash
          docker pull harz-storage:${{ steps.version.outputs.version_number }}
          \`\`\`

          ## Helm Deployment
          \`\`\`bash
          helm upgrade --install harz-storage ./harz-storage-${{ steps.version.outputs.version_number }}.tgz --set image.tag=${{ steps.version.outputs.version_number }}
          \`\`\`

          **Note:** This release requires merging PR for version bump to complete the release process." \
            sbom-${{ steps.version.outputs.version_number }}.spdx.json \
            trivy-results-${{ steps.version.outputs.version_number }}.sarif \
            security-audit-${{ steps.version.outputs.version_number }}.json \
            harz-storage-${{ steps.version.outputs.version_number }}.tgz \
            checksums-${{ steps.version.outputs.version_number }}.txt
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
